### ISSUE TITLE
Switching to Sass

### ISSUE THREAD

**Issue by dmyers** [holman/left#31]
Is it worth switching to Sass now that [GitHub Pages supports it](https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0)?

**Comment by holman** [comment]
Yup! That'd be lovely. I wonder if I have the original on my hard drive somewhere.

**Comment by dmyers** [comment]
Do you have a preference on Sass or Scss? I come from Less (Twitter Boostrap) so I don't know which is  better.

Could it be as simple as using [convert2sass](http://css2sass.herokuapp.com)?

**Comment by holman** [comment]
I'd prefer SCSS, really.

**Comment by holman** [comment]
Fixed!
