### ISSUE TITLE
jekyll-sitemap from _config.yml causing error on Jekyll Serve

### ISSUE THREAD

**Issue by KitN** [holman/left#34]
I forked the site and cloned it into a folder on my computer. I performed `jekyll serve` without making any changes and the serve ran into an error. Here is the relevant error message from `jekyll doctor`

```
Configuration file: /home/user/www/_config.yml
/home/user/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require':
 cannot load such file -- jekyll-sitemap (LoadError)
```

I'm not very experienced with Ruby, so I don't know if this is my fault or if it is a real issue with the repo.

**Comment by holman** [comment]
Try running `gem install jekyll-sitemap`.

**Comment by KitN** [comment]
I ran `gem install jekyll-sitemap` and then one other gem was missing, `rdiscount` so I ran `gem install rdiscount` and the site is serving fine now. :+1: 

I do wonder if it would be helpful to include these in a gemfile in the main left repository for others with the same dependency problems., but I'm new to ruby (and github and jekyll and apache and just about everything else in my website aha :confused: : ) so maybe its not worth changing.

**Comment by ghost** [comment]
it's perfect now. Helpful
