### ISSUE TITLE
rdiscount -> kramdown

### ISSUE THREAD

**Issue by katyhuff** [holman/left#43]
First, thanks for left. I like and use and rely on it. 

Now... I see that github is no longer going to support rdiscount in jekyll pages (you're aware of this too, I see: https://github.com/github/pages-gem/issues/179). That's cool. I'm down with that. Trouble is, moving from rdiscount to kramdown in left has mysteriously screwed up my index page rendering. This could totally be my flawed use of left. I hope you'll let me know if that's the case. Here's the [source](http://github.com/thehackerwithin/berkeley/tree/gh-pages).

I had my index page looking like:
<img width="957" alt="screen shot 2016-02-03 at 8 20 24 pm" src="https://cloud.githubusercontent.com/assets/393899/12805809/52e1b0aa-cab4-11e5-8383-b817395879f4.png">

I made (more or less) the following changes to my config.yml file:

```
- markdown: rdiscount
- rdiscount:
-     extensions: [smart]
+ markdown: kramdown
+ kramdown:
+    input: GHM
+    hard_wrap: false
```

Now, it renders terribly. 

<img width="964" alt="screen shot 2016-02-03 at 8 19 52 pm" src="https://cloud.githubusercontent.com/assets/393899/12805813/55b9c704-cab4-11e5-91b3-6524eb40b66a.png">

Any idea what I should do on that front?

**Comment by holman** [comment]
This brings up a good point; I went and updated Left to use Jekyll 3 in #44. That might be helpful for you. I'm also going to take a peek at your stuff next- brb!

**Comment by holman** [comment]
Lookin' sharp to me!

<img width="1114" alt="screen shot 2016-02-03 at 8 54 42 pm" src="https://cloud.githubusercontent.com/assets/2723/12806171/637b2a50-cab8-11e5-99fe-331ade0b7414.png">

...did you restart your server? :) Are there any errors that the server is spitting out?

**Comment by katyhuff** [comment]
I changed it back to rdiscount since it's a live site and I didn't want it
to be ugly all night. (
https://github.com/thehackerwithin/berkeley/blob/gh-pages/_config.yml).
If you make just the one change, you'll see it fail:

```
- markdown: rdiscount
+ markdown: kramdown
```

I'll push an ugly version to katyhuff.github.io/berkeley/

On Wed, Feb 3, 2016 at 8:55 PM, Zach Holman notifications@github.com
wrote:

> Lookin' sharp to me!
> 
> [image: screen shot 2016-02-03 at 8 54 42 pm]
> https://cloud.githubusercontent.com/assets/2723/12806171/637b2a50-cab8-11e5-99fe-331ade0b7414.png
> 
> ...did you restart your server? :) Are there any errors that the server is
> spitting out?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/holman/left/issues/43#issuecomment-179640068.

## 

http://katyhuff.github.com

**Comment by katyhuff** [comment]
alright [katyhuff.github.io/berkeley/](http://katyhuff.github.io/berkeley/) is kramdown-ified now.

**Comment by holman** [comment]
So I can reproduce it and it's really strange. Going to keep looking at it because I'm pretty sure it's something obvious that I'm missing.

**Comment by holman** [comment]
Cool, figured it out:

``` diff
diff --git a/_config.yml b/_config.yml
index adad3c4..7cfd329 100644
--- a/_config.yml
+++ b/_config.yml
@@ -4,6 +4,7 @@ markdown: rdiscount
 kramdown:
   input: GFM
   hard_wrap: false
+  parse_block_html: true
 github: thehackerwithin
 url: http://thehackerwithin.github.com/berkeley 
 name: Hacker Within
@@ -12,4 +13,3 @@ description: An initial blog and site for THW at UCB
 twitter: hackerwithin
 gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
 disqus_username: hackerwithinadmin
```

I noticed that it didn't parse the Markdown when wrapped in an HTML tag. According to [the kramdown docs](http://kramdown.gettalong.org/options.html#option-parse-block-html), `parse_block_html` is disabled by default, so it was seeing the HTML tag and bailing. Guess those Markdown renderers aren't _quite_ the same.

Let me know if this works for you!

**Comment by katyhuff** [comment]
Heck yes!! 
Thanks @holman !

**Comment by katyhuff** [comment]
Hi there @holman . I think we have to reopen this. It looks like they finished the transition to kramdown yesterday. I assume that change caused things to look ugly again:

for me: https://thehackerwithin.github.com/berkeley/upcoming.html
and for you: https://zachholman.com/left/

I tried a couple of changes to my config file such as:

```
 markdown: kramdown
+highlighter: rouge
 kramdown:
   input: GFM
   hard_wrap: false
   parse_block_html: true
+  parse_span_html: true
+  auto_ids: true
+  smart_quotes: lsquo,rsquo,ldquo,rdquo
+  enable_coderay: false
+  syntax_highlighter: rouge
```

none of these additions helped.

**Comment by holman** [comment]
Yours is fixed if you hit the http version instead of https; you have insecure content warnings so your browser isn't rendering the styles.

I'm fixing zachholman.com/left as soon as anything remotely works on github.

**Comment by katyhuff** [comment]
oh geez.  ![bitmoji](https://render.bitstrips.com/v2/cpanel/7258113-116454032_9-s1-v1.png?palette=1&width=246)

Right you are. Sorry for bugging you about that.
