### ISSUE TITLE
Main branch wrong?

### ISSUE THREAD

**Issue by dmyers** [holman/left#5]
I couldn't for the life of me figure out why my site wasn't building.

I started searching and it looks like the `gh-pages` is for project pages and master is for user pages? I renamed my main branch to `master` and it started building with Jekyll. :bomb:

Source: http://stackoverflow.com/questions/7555837/publish-jekyll-generated-to-gh-pages-and-not-overwite-the-git-in-site/10876328#10876328

Thanks again for open sourcing this! :+1:

**Comment by holman** [comment]
Hm. Interesting.

This is a weird thing since I eventually will want a `gh-pages` branch on _this_ project (once we fix the bug on Pages and let me generate non-CNAME'd project files), but you're right; `master` makes the most sense for people cloning it. I'll make the change.
